Updated Deploy job

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -78,7 +78,7 @@ jobs:
         uses: actions/upload-pages-artifact@v3
         with:
           path: ./_site
-
+        
   # Deploy Job
   deploy:
     environment:
@@ -94,6 +94,10 @@ jobs:
           name: flutter-web-build
           path: ./build/web
 
+      - name: List files in build/web
+        if: env.skip_flutter_build == 'false'
+        run: ls -R ./build/web
+
       - name: Deploy Flutter Web App
         if: env.skip_flutter_build == 'false'
         id: flutter_deploy
@@ -101,6 +105,15 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./build/web
+
+      - name: Download Jekyll Site Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: jekyll-site
+          path: ./_site
+
+      - name: List files in _site
+        run: ls -R ./_site
 
       - name: Deploy Jekyll Site
         id: jekyll_deploy
@@ -111,13 +124,12 @@ jobs:
 
       - name: Check for errors
         run: |
-          if [ -f ./web/index.html ]; then
+          if [ -f ./build/web/index.html ]; then
             echo "Flutter deployment successful."
           else
             echo "Flutter deployment failed."
-            exit 1
+          exit 1
           fi
-          
 
           if [ -f ./_site/index.html ]; then
             echo "Jekyll deployment successful."
@@ -125,3 +137,50 @@ jobs:
             echo "Jekyll deployment failed."
             exit 1
           fi
+
+  # # Deploy Job
+  # deploy:
+  #   environment:
+  #     name: github-pages
+  #     url: ${{ steps.deployment.outputs.page_url }}
+  #   runs-on: ubuntu-latest
+  #   needs: [build_flutter, build_jekyll]
+  #   steps:
+  #     - name: Download Flutter Web Build Artifact
+  #       if: env.skip_flutter_build == 'false'
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: flutter-web-build
+  #         path: ./build/web
+
+  #     - name: Deploy Flutter Web App
+  #       if: env.skip_flutter_build == 'false'
+  #       id: flutter_deploy
+  #       uses: actions/deploy-pages@v4
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         publish_dir: ./build/web
+
+  #     - name: Deploy Jekyll Site
+  #       id: jekyll_deploy
+  #       uses: actions/deploy-pages@v4
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         publish_dir: ./_site
+
+  #     - name: Check for errors
+  #       run: |
+  #         if [ -f ./web/index.html ]; then
+  #           echo "Flutter deployment successful."
+  #         else
+  #           echo "Flutter deployment failed."
+  #           exit 1
+  #         fi
+          
+
+  #         if [ -f ./_site/index.html ]; then
+  #           echo "Jekyll deployment successful."
+  #         else
+  #           echo "Jekyll deployment failed."
+  #           exit 1
+  #         fi
